### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by pokecheater** [richard-livingston/json-view#4]
Hey richard-livingston,

I really like this package, it is fast, simple and it matches exactly what I need :). Sadly I can not use it because there is no license file that allows me to use it. Plz create one with MIT if you want that anybody is allowed to use your package within their projects. Elsewise a lot of people will not use it exactly because of this issue.

Greetz

**Comment by pokecheater** [comment]
Hey richard are you still alive? :)

**Comment by pokecheater** [comment]
Okay,
after waiting nearly a full month for an answer we decided to remove your package because we can not be sure that it will be legal to use without any form of license for it. 

For anyone else who is struggling with this issue I recommend to use the following npm package. It seems to be updated regulary and the licensing-question is clear (apache 2.0). Furthermore it has some really fancy functions like drag and drop and a search bar :).

https://www.npmjs.com/package/jsoneditor

**Comment by richard-livingston** [comment]
Hi there, sorry for the delayed response. I've added an MIT license to the project and the package.json, I wil republish the project on NPM soon.

Thanks
